# Plain wrong :)
Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1

# Just annoying
Metrics/AbcSize:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

# Multiline regexes
Style/RegexpLiteral:
  Enabled: false