Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Metrics/AbcSize:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false